import React, { useState } from 'react';
import { ServerSettings } from '../types';
import { Download, Package, Server, Code, FileCode2 } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface Props {
  settings: ServerSettings;
  onSettingsChange: (settings: ServerSettings) => void;
}

export default function ServerSetup({ settings, onSettingsChange }: Props) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleChange = (key: keyof ServerSettings, value: any) => {
    onSettingsChange({ ...settings, [key]: value });
  };

  const generateZip = async () => {
    setIsGenerating(true);
    
    try {
      const zip = new JSZip();
      
      // 1. Generate server.properties
      let propsContent = `#Minecraft server properties\n#Generated by SkyHub Dashboard\n`;
      propsContent += `motd=${settings.motd}\n`;
      propsContent += `max-players=${settings.maxPlayers}\n`;
      propsContent += `server-port=${settings.serverPort}\n`;
      propsContent += `gamemode=${settings.gamemode}\n`;
      propsContent += `difficulty=${settings.difficulty}\n`;
      propsContent += `pvp=${settings.pvp}\n`;
      propsContent += `hardcore=${settings.hardcore}\n`;
      propsContent += `enable-command-block=${settings.enableCommandBlock}\n`;
      propsContent += `online-mode=${settings.onlineMode}\n`;
      propsContent += `level-name=${settings.levelName}\n`;
      if (settings.levelSeed) propsContent += `level-seed=${settings.levelSeed}\n`;
      
      zip.file('server.properties', propsContent);

      // 2. eula.txt
      zip.file('eula.txt', 'eula=true\n');

      // 3. start script (sh)
      let jarName = `server.jar`;
      if (settings.type === 'paper') jarName = `paper-${settings.version}.jar`;
      
      zip.file('start.sh', `#!/bin/sh\njava -Xmx2G -Xms2G -jar ${jarName} nogui\n`);
      zip.file('start.bat', `java -Xmx2G -Xms2G -jar ${jarName} nogui\npause\n`);
      
      // We don't magically bundle the server.jar to save bandwidth, we would just put a read me
      zip.file('README.txt', `SkyHub Server Setup\n1. Download the ${settings.type} JAR for version ${settings.version}.\n2. Rename it to ${jarName} and place it in this folder.\n3. Run start.sh or start.bat.\n4. To expose using cloudflare tunnel (dashboard.skyhub.my.id), run:\n   cloudflared tunnel run my-minecraft-tunnel\n`);

      const content = await zip.generateAsync({ type: 'blob' });
      saveAs(content, `skyhub-server-${settings.type}-${settings.version}.zip`);

    } catch (err) {
      console.error(err);
      alert("Failed to generate zip");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden">
      <header className="h-20 bg-slate-900 border-b border-slate-700 flex items-center justify-between px-8 shrink-0">
         <div className="flex items-center gap-3">
           <Package size={24} className="text-blue-500" />
           <div className="flex flex-col">
             <span className="text-sm font-bold text-white uppercase tracking-wider">Server Setup & Export</span>
             <span className="text-[10px] text-slate-400">Configure core server settings & download bundle</span>
           </div>
         </div>
      </header>

      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Core Settings */}
          <div className="lg:col-span-2 flex flex-col gap-6">
            <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-5 shadow-sm">
              <h3 className="text-xs font-bold text-white mb-4 flex items-center gap-2 uppercase tracking-wider border-b border-slate-700/50 pb-2">
                <Server size={14} className="text-slate-400" /> Software Selection
              </h3>
              
              <div className="space-y-5">
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Server Type</label>
                  <div className="flex flex-wrap gap-2">
                    {['vanilla', 'paper', 'spigot', 'forge', 'fabric'].map(type => (
                      <button
                        key={type}
                        onClick={() => handleChange('type', type)}
                        className={`capitalize py-2 px-4 rounded text-[11px] font-bold transition-colors border ${
                          settings.type === type 
                            ? 'bg-blue-600/20 border-blue-500/50 text-blue-400' 
                            : 'bg-slate-900 border-slate-700 text-slate-400 hover:bg-slate-700'
                        }`}
                      >
                        {type}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Version</label>
                    <select 
                      value={settings.version}
                      onChange={(e) => handleChange('version', e.target.value)}
                      className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-xs text-white outline-none focus:border-blue-500"
                    >
                      <option value="1.20.4">1.20.4 (Recommended)</option>
                      <option value="1.20.2">1.20.2</option>
                      <option value="1.19.4">1.19.4</option>
                      <option value="1.18.2">1.18.2</option>
                      <option value="1.16.5">1.16.5</option>
                      <option value="1.12.2">1.12.2</option>
                    </select>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Server Port</label>
                    <input 
                      type="number" 
                      value={settings.serverPort}
                      onChange={(e) => handleChange('serverPort', parseInt(e.target.value) || 25565)}
                      className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-xs text-white outline-none focus:border-blue-500"
                    />
                  </div>
                </div>
              </div>
            </div>
            
            <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-5 shadow-sm">
               <h3 className="text-xs font-bold text-white mb-3 uppercase tracking-wider">MOTD (Message of the Day)</h3>
               <input 
                 type="text" 
                 value={settings.motd}
                 onChange={(e) => handleChange('motd', e.target.value)}
                 className="w-full bg-slate-900 border border-slate-700 rounded p-3 text-emerald-400 font-mono text-[11px] outline-none focus:border-blue-500"
               />
               <p className="text-[10px] text-slate-500 mt-2 font-medium">This message appears in the multiplayer server list.</p>
            </div>
          </div>

          {/* Action Panel */}
          <div className="flex flex-col">
            <div className="bg-blue-900/10 border border-blue-500/20 rounded-lg p-5 shadow-sm h-full flex flex-col">
              <h3 className="text-xs font-bold text-white mb-2 uppercase tracking-wider">Build Package</h3>
              <p className="text-[11px] text-blue-300 leading-relaxed mb-6">
                Download the base configuration ZIP file. Extract this on your yupra.net panel to securely configure your server instance.
              </p>
              
              <div className="space-y-2.5 mb-8 flex-1">
                <div className="flex items-center gap-2 px-3 py-2 bg-slate-900/50 rounded border border-slate-800 text-[11px] text-slate-400 font-mono">
                  <FileCode2 size={12} className="text-slate-500"/> server.properties
                </div>
                <div className="flex items-center gap-2 px-3 py-2 bg-slate-900/50 rounded border border-slate-800 text-[11px] text-slate-400 font-mono">
                  <FileCode2 size={12} className="text-slate-500"/> eula.txt
                </div>
                <div className="flex items-center gap-2 px-3 py-2 bg-slate-900/50 rounded border border-slate-800 text-[11px] text-slate-400 font-mono">
                  <Code size={12} className="text-slate-500"/> start.sh / start.bat
                </div>
              </div>

              <button 
                onClick={generateZip}
                disabled={isGenerating}
                className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-600/50 text-white rounded text-xs font-bold shadow-lg transition-colors flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    <Download size={14} />
                    GENERATE & EXPORT
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
